### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by daveruse** [flopp/StravaExportToGPX#8]
Hi,

Trying to list my activity types and am getting the following error.

Python: 3.8.5
gpslabel: 1.7.0

`user-name:StravaExportToGPX user-name$ ./strava2gpx.py --input export_14713437.zip --list-types
Activity types found in export_14713437.zip:
Traceback (most recent call last):
  File "./strava2gpx.py", line 267, in <module>
    main()
  File "./strava2gpx.py", line 212, in main
    for activity in get_activities(zip_file, activities_csv)
  File "./strava2gpx.py", line 114, in get_activities
    return get_activities(None, unzipped_file.name)
  File "./strava2gpx.py", line 122, in get_activities
    raise Exception(
Exception: Unexpected header items in activities CSV file (expeciting 10 or 11 items): ['Activity ID', 'Activity Date', 'Activity Name', 'Activity Type', 'Activity Description', 'Elapsed Time', 'Distance', 'Relative Effort', 'Commute', 'Activity Gear', 'Filename', 'Athlete Weight', 'Bike Weight', 'Moving Time', 'Max Speed', 'Average Speed', 'Elevation Gain', 'Elevation Loss', 'Elevation Low', 'Elevation High', 'Max Grade', 'Average Grade', 'Average Positive Grade', 'Average Negative Grade', 'Max Cadence', 'Average Cadence', 'Max Heart Rate', 'Average Heart Rate', 'Max Watts', 'Average Watts', 'Calories', 'Max Temperature', 'Average Temperature', 'Total Work', 'Number of Runs', 'Uphill Time', 'Downhill Time', 'Other Time', 'Perceived Exertion', 'translation missing: en-US.lib.export.portability_exporter.activities.horton_values.type', 'translation missing: en-US.lib.export.portability_exporter.activities.horton_values.start_time', 'Weighted Average Power', 'Power Count', 'Prefer Perceived Exertion', 'Perceived Relative Effort', 'Total Weight Lifted', 'From Upload', 'Grade Adjusted Distance', 'Weather Observation Time', 'Weather Condition', 'Weather Temperature', 'Apparent Temperature', 'Dewpoint', 'Humidity', 'Weather Pressure', 'Wind Speed', 'Wind Gust', 'Wind Bearing', 'Precipitation Intensity', 'Sunrise Time', 'Sunset Time', 'Moon Phase', 'Bike', 'Gear', 'Precipitation Probability', 'Precipitation Type', 'Cloud Cover', 'Weather Visibility', 'UV Index', 'Weather Ozone', 'translation missing: en-US.lib.export.portability_exporter.activities.horton_values.jump_count', 'translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_grit', 'translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_flow']`

**Comment by daveruse** [comment]
Hi, just following up on this issue - still have the same problem.

**Comment by jacobfeng** [comment]
Same here.

**Comment by atoponce** [comment]
Confirmed.

- Debian unstable
- Python 3.10.4
- gpsbabel 1.8.0

```
Activity types found in strava-export/export_67079323.zip:
Traceback (most recent call last):
  File "/home/atoponce/src/StravaExportToGPX/./strava2gpx.py", line 267, in <module>
    main()
  File "/home/atoponce/src/StravaExportToGPX/./strava2gpx.py", line 212, in main
    for activity in get_activities(zip_file, activities_csv)
  File "/home/atoponce/src/StravaExportToGPX/./strava2gpx.py", line 114, in get_activities
    return get_activities(None, unzipped_file.name)
  File "/home/atoponce/src/StravaExportToGPX/./strava2gpx.py", line 122, in get_activities
    raise Exception(
Exception: Unexpected header items in activities CSV file (expeciting 10 or 11 items): ['Activity ID', 'Activity Date', 'Activity Name', 'Activity Type', 'Activity Description', 'Elapsed Time', 'Distance', 'Max Heart Rate', 'Relative Effort', 'Commute', 'Activity Gear', 'Filename', 'Athlete Weight', 'Bike Weight', 'Moving Time', 'Max Speed', 'Average Speed', 'Elevation Gain', 'Elevation Loss', 'Elevation Low', 'Elevation High', 'Max Grade', 'Average Grade', 'Average Positive Grade', 'Average Negative Grade', 'Max Cadence', 'Average Cadence', 'Average Heart Rate', 'Max Watts', 'Average Watts', 'Calories', 'Max Temperature', 'Average Temperature', 'Total Work', 'Number of Runs', 'Uphill Time', 'Downhill Time', 'Other Time', 'Perceived Exertion', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.type">Type</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.start_time">Start Time</span>', 'Weighted Average Power', 'Power Count', 'Prefer Perceived Exertion', 'Perceived Relative Effort', 'Total Weight Lifted', 'From Upload', 'Grade Adjusted Distance', 'Weather Observation Time', 'Weather Condition', 'Weather Temperature', 'Apparent Temperature', 'Dewpoint', 'Humidity', 'Weather Pressure', 'Wind Speed', 'Wind Gust', 'Wind Bearing', 'Precipitation Intensity', 'Sunrise Time', 'Sunset Time', 'Moon Phase', 'Bike', 'Gear', 'Precipitation Probability', 'Precipitation Type', 'Cloud Cover', 'Weather Visibility', 'UV Index', 'Weather Ozone', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.jump_count">Jump Count</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_grit">Total Grit</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_flow">Avg Flow</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.flagged">Flagged</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_elapsed_speed">Avg Elapsed Speed</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.dirt_distance">Dirt Distance</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_distance">Newly Explored Distance</span>', '<span class="translation_missing" title="translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_dirt_distance">Newly Explored Dirt Distance</span>']
```

**Comment by Djailla** [comment]
Same issue, I guess the format of the exported CSV has changed
